import Head from "next/head";
import React from "react";

interface LayoutParams {
  title?: string;
  children: React.ReactNode;
}

export const Layout = ({ title, children }: LayoutParams) => {
  return (
    <div className="flex flex-col min-h-screen bg-slate-900 text-white gap-8">
      <Head>
        <title>{title ?? "Voodoo Tickets"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </div>
  );
};
